version: 0.2

phases: 
    install:
        runtime-versions:
            python: 3.8
        commands:
            - echo "installing something"
    pre_build:
        commands: 
            - echo "we are in the pre build phase"
    build:
        commands:
            - echo "we are in the build block"
            - echo "we will run some tests"
            - grep -Fq "user1" Lambda/app.py
            - aws cloudformation package --template template.yml --s3-bucket aws-sam-cli-managed-default-samclisourcebucket-14u44ibuo56vd --output-template packaged-template.json
    post_build:
        commands:
            - echo "we are in the post build phase!"

artifacts:
  type: zip
  primary-artifacts:
    artifact1:
      files:
        - packaged-template.json