version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "my-sam-app"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-14u44ibuo56vd"
s3_prefix = "my-sam-app"
region = "eu-west-2"
# profile = "default"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
myTable = "my-sam-app-MyTable-1EPHJ8ADIH7T9"
